Fix summary with multiple test suites and skipped tests
cpisciotta/xcbeautify pull request #65
Opened 2022-01-16 05:42 UTC by joshdholtz

## Motivation
Fixes https://github.com/fastlane/fastlane/pull/19629#issuecomment-1013511227

The test summary printed after a run was showing wrong results if:
- Multiple test suites were being run
- Any tests were skipped

Expected: `Tests Passed: 0 failed, 955 total (12.187 seconds)`
Actual: `Tests Passed: 0 failed, 56 total (0.324 seconds)`

The issue was because the test summary line parser assumed that there was only one line summary being printed. The line looks like 👇 

```sh
Executed 8 tests, with 4 failures (0 unexpected) in 0.154 (0.155) seconds
```

However... this line gets printed multiple times after each suite gets run 👇 

```sh
Test Case '-[Tests_iOS.Tests_iOS testExample5ThatSometimesFails]' failed (0.019 seconds).                                                              
Test Suite 'Tests_iOS' failed at 2022-01-15 21:31:49.073.                                                                                              
         Executed 8 tests, with 4 failures (0 unexpected) in 0.154 (0.155) seconds                                                                     
Test Suite 'Tests iOS.xctest' failed at 2022-01-15 21:31:49.073.                                                                                       
         Executed 8 tests, with 4 failures (0 unexpected) in 0.154 (0.155) seconds                                                                     
Test Suite 'All tests' failed at 2022-01-15 21:31:49.073.                                                                                              
         Executed 8 tests, with 4 failures (0 unexpected) in 0.154 (0.156) seconds
```

There is also a case that was unaccounted when tests were skipped 👇 

```sh
Executed 56 tests, with 3 tests skipped and 0 failures (0 unexpected) in 1.019 (1.029) seconds 
```

## Description
- Introduced 2 new line matchers for when a suite is finished for "All tests"
- Introduced 1 new line matcher for "Executed with skipped tests"

**Previously**, the `testSummary` in `Parser` would get override by the latest summary which was the root cause of this issue.

**Now**, a `testSummary` will only get parsed when it follows either `Test Suite 'All tests' passed at` or `Test Suite 'All tests' failed at`. There can also be multiple summaries so this will also add all the summaries together for:
- test count
- skipped count
- failure count
- unexpected count
- time

It also adds logic now for parsing the two different variation of the "executed" lines:
- `Executed 8 tests, with 4 failures (0 unexpected) in 0.154 (0.155) seconds `
- `Executed 56 tests, with 3 tests skipped and 0 failures (0 unexpected) in 1.019 (1.029) seconds `

2022-01-16 16:36 UTC, adellibovi requested changes
Thanks @joshdholtz for the PR ☺️.
It would be great if we can add a test so we don't regress on this 🙏🏻

2022-01-16 16:52 UTC, joshdholtz commented
On it!

2022-01-18 08:14 UTC, adellibovi approved these changes
Thanks @joshdholtz , LGTM! 🥳  cc @tuist/core

2022-01-18 08:24 UTC, danyf90 approved these changes

2022-01-18 08:24 UTC, danieleformichelli commented on Sources/XcbeautifyLib/Parser.swift
> +        }
```suggestion
        guard needToRecordSummary else {
            return
        }
```

2022-01-18 08:24 UTC, danieleformichelli commented on Tests/XcbeautifyLibTests/XcbeautifyLibTests.swift
> +        XCTAssertNotNil(parser.summary)
I would unwrap it here to simplify subsequent code
```suggestion
        let summary = try XCTUnwrap(parser.summary)
```

2022-01-20 01:28 UTC, joshdholtz commented
Any idea why two tests failed on Ubuntu? 😬

2022-01-20 04:06 UTC, luispadron commented
> Any idea why two tests failed on Ubuntu? 😬

I’m not entirely sure but the tests that are failing are:

    ✖ testExecuted, XCTAssertTrue failed - 
48
    ✖ testExecuted, XCTUnwrap failed: expected non-nil value of type "TestSummary" -

2022-01-21 13:15 UTC, pepicrft commented
> Any idea why two tests failed on Ubuntu? 😬

I recommend running them in Docker:

```bash
docker run --rm \
    --volume "$(pwd):/package" \
    --workdir "/package" \
    swift:5.5 \
    /bin/bash -c \
    "swift package fetch && swift test --build-path ./.build/linux"
```

If it fails consistently on CI it's possible it's a legit error due to implementations that are coupled to the OS.

2022-02-25 07:16 UTC, merged

2022-02-25 07:24 UTC, thii commented
Thanks @joshdholtz!