Parse name and unitname for measurements
cpisciotta/xcbeautify pull request #73
Opened 2022-04-29 20:21 UTC by Cyberbeni

Resolves #25

Test data:
[test_output.txt](https://github.com/tuist/xcbeautify/files/8594509/test_output.txt)

2022-09-18 11:44 UTC, thii requested changes
@Cyberbeni Can you add a simple test? You can use the output in your example.

2022-09-22 12:45 UTC, Cyberbeni commented
Separate issue, but the os checks should probably be `can(macOS)` everywhere. I don't have a Swift for Windows setup but I suspect it produces the same as Linux.

2022-09-22 14:05 UTC, thii commented on Tests/XcbeautifyLibTests/XcbeautifyLibTests.swift
> +        XCTAssertEqual(formatted, #"    ◷ test_subscribing_2senders_notificationName measured (5407.634 KB ±45.772% -- High Water Mark For Heap Allocations)"#)
Seems like it's hiding a lot of info. I guess it's fine since this is just a beautifier tool.

2022-09-22 14:07 UTC, thii commented
Yeah but since we only test on Linux and macOS so it can be only either Linux or macOS.

2022-09-22 14:07 UTC, thii approved these changes

2022-09-22 14:07 UTC, merged